### PR TITLE
fix issue where certs get re-created immediately after deletion

### LINKED ISSUE #209: NifiUserController reconciles certs after NifiUser deletion
### What steps will reproduce the bug?

For me, it's easiest to reproduce by deploying a `NifiCluster` with `NifiUser`s using ArgoCD, letting nifikop reconcile certificates for each user. When a cluster is deleted, there's a race condition that occurs where ArgoCD will delete (or mark for deletion) all of the nifikop resources. 

The nifi user controller hits a condition where a `NifiUser` is marked for deletion and the controller revokes certs and deletes secrets. But then it immediately reconciles the certs & secrets again which re-creates them. The code which does this is [here](https://github.com/konpyutaika/nifikop/blob/master/controllers/nifiuser_controller.go#L176-L229). This causes NifiCluster deletions in ArgoCD to hang because the operator is re-creating resources that had just been deleted.

1. Deploy a secure `NifiCluster` with one or more `NifiUser`s. Note that each node is treated as a `NifiUser` and has certs generated for them.
2. Delete the cluster deployment in ArgoCD & observe that `NifiUser` certs and secrets get deleted and immediately re-created.

### What is the expected behavior?

The nifi user controller should only reconcile user certs if the associated `NifiUser` is not marked for deletion.

### What do you see instead?

The nifi user controller reconciles user certs regardless of whether the associated `NifiUser` is marked for deletion.

### Possible solution

The nifi user controller should reconcile user certificates only if the associated `NifiUser` is not marked for deletion.

### NiFiKop version

v0.15.0-release

### Golang version

go1.18

### Kubernetes version

1.24

### NiFi version

1.18.0

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by michael81877**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| API breaks?     | no
| Deprecations?   | no
| Related tickets | fixes #209 
| License         | Apache 2.0

### What's in this PR?

The nifi user controller hits a condition where a `NifiUser` is marked for deletion and the controller revokes certs and deletes secrets. However, it then immediately reconciles the certs & secrets again which re-creates them. The code which does this is [here](https://github.com/konpyutaika/nifikop/blob/master/controllers/nifiuser_controller.go#L176-L229). This causes `NifiCluster` deletions in ArgoCD to hang and not delete cleanly because the operator is re-creating resources that had just been deleted.

I tested this by deploying a `NifiCluster` via ArgoCD. Once it came all the way up & certs had been generated, I deleted the cluster in ArgoCD. Prior to this change, the deletion would get hung up on Certificates/Secrets that the operator re-created. With this change, clusters are gracefully deleted by ArgoCD and re-created.

### Why?

To correctly reconcile resources associated with `NifiUser` objects.

### Checklist

- [x] Implementation tested
- [x] Error handling code meets the [guideline](docs/error-handling-guide.md)
- [x] Logging code meets the guideline
- [x] User guide and development docs updated (if needed)
- [x] Append changelog with changes

### CODE REVIEW

File: controllers/nifiuser_controller.go [hunk 1]
```diff
@@ -173,60 +173,61 @@ func (r *NifiUserReconciler) Reconcile(ctx context.Context, req ctrl.Request) (c
...
-		// check if marked for deletion
+		// check if marked for deletion. Otherwise, reconcile the certificate
 		if k8sutil.IsMarkedForDeletion(instance.ObjectMeta) {
 			r.Log.Info("Nifi user is marked for deletion, revoking certificates and removing finalizers.",
 				zap.String("user", instance.Name))
 			if err = pkiManager.FinalizeUserCertificate(ctx, instance); err != nil {
 				return RequeueWithError(r.Log, "failed to finalize certificate for user "+instance.Name, err)
 			}
-		}
-
```
Comment (michael81877) [inline controllers/nifiuser_controller.go:184]: This looks like a large change, but it's just wrapping this block of code in an `else`. That is, only reconcile certificates if the `NifiUser` is not marked for deletion.

**Review by r65535 — APPROVED** [review]
I've run into this bug regularly too - good find!
LGTM!

**Review by erdrix — APPROVED** [review]
